server:
  port: 8082
database:
  serverName: localhost
  port: 3306
  user: root
  password: password
  schema: crm-db

spring:
  application:
    name: crm-api
  datasource:
    url: jdbc:mysql://${database.serverName}:${database.port}/${database.schema}
    username: "${database.user}"
    password: "${database.password}"
    hikari:
      maximumPoolSize: 50
      maxLifeTime: 840000
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration/schema, classpath:db/migration/data
    validate-on-migration: true